apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flaskpostgresapps.msimonsen.dev
spec:
  scope: Namespaced
  group: msimonsen.dev
  names:
    kind: FlaskPostgresApp
    plural: flaskpostgresapps
    singular: flaskpostgresapp
    shortNames:
      - fpg
      - fpgs
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true